name: ags_school_system
description: AGS School System desktop application for teacher management and more.
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.7
  go_router: ^13.2.2
  intl: ^0.18.1
  data_table_2: ^2.5.9
  fl_chart: ^0.66.2
  drift: ^2.17.0
  equatable: ^2.0.5
  sqlite3: ^2.4.3
  sqlite3_flutter_libs: ^0.5.21
  path_provider: ^2.1.2
  pdf: ^3.10.7
  printing: ^5.12.0

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  drift_dev: ^2.17.0
  riverpod_generator: ^2.3.5
  freezed: ^2.4.6
  flutter_lints: ^4.0.0
